# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers


# 1-nl-nm-ns-ynetwork-mid-0-140-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 140

# 1-nl-nm-ns-ynetwork-mid-0-280-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280

# 1-nl-nm-ns-ynetwork-mid-0-420-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420

# 1-nl-nm-ns-ynetwork-mid-0-560-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560

# 1-nl-nm-ns-ynetwork-mid-0-700-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700

# 1-nl-nm-ns-ynetwork-mid-0-840-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840


# 1-nl-nm-ns-ynetwork-mid-0-140-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 140

# 1-nl-nm-ns-ynetwork-mid-0-280-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280

# 1-nl-nm-ns-ynetwork-mid-0-420-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420

# 1-nl-nm-ns-ynetwork-mid-0-560-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560

# 1-nl-nm-ns-ynetwork-mid-0-700-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700

# 1-nl-nm-ns-ynetwork-mid-0-840-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840


# 1-nl-nm-ns-ynetwork-mid-0-420-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420

# 1-nl-nm-ns-ynetwork-mid-0-560-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560

# 1-nl-nm-ns-ynetwork-mid-0-700-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700

# 1-nl-nm-ns-ynetwork-mid-0-840-SHen-AVen-2: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840

# 1-yl-ym-ys-ynetwork-mid-0-140-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 140
# 1-yl-ym-ys-ynetwork-mid-0-280-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280
# 1-yl-ym-ys-ynetwork-mid-0-420-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420
# 1-yl-ym-ys-ynetwork-mid-0-560-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560
# 1-yl-ym-ys-ynetwork-mid-0-700-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700
# 1-yl-ym-ys-ynetwork-mid-0-840-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840

# 1-yl-ym-ys-ynetwork-mid-0-980-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 980
# 1-yl-ym-ys-ynetwork-mid-0-1120-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1120
# 1-yl-ym-ys-ynetwork-mid-0-1260-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1260

# 1-nl-nm-ns-ynetwork-mid-0-140-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 140
# 1-nl-nm-ns-ynetwork-mid-0-280-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280
# 1-nl-nm-ns-ynetwork-mid-0-420-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420
# 1-nl-nm-ns-ynetwork-mid-0-560-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560
# 1-nl-nm-ns-ynetwork-mid-0-700-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700
# 1-nl-nm-ns-ynetwork-mid-0-840-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840

# 1-nl-nm-ns-ynetwork-mid-0-980-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 980
# 1-nl-nm-ns-ynetwork-mid-0-1120-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1120
# 1-nl-nm-ns-ynetwork-mid-0-1260-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1260

# 1-nl-nm-ns-ynetwork-mid-0-140-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 140
# 1-nl-nm-ns-ynetwork-mid-0-280-SHen-AVen-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280
# 1-nl-nm-ns-ynetwork-mid-0-420-SHen-AVen-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420
# 1-nl-nm-ns-ynetwork-mid-0-560-SHen-AVen-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560
# 1-nl-nm-ns-ynetwork-mid-0-700-SHen-AVen-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700
# 1-nl-nm-ns-ynetwork-mid-0-840-SHen-AVen-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840
# 1-nl-nm-ns-ynetwork-mid-0-980-SHen-AVen-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 980
# 1-nl-nm-ns-ynetwork-mid-0-1120-SHen-AVen-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1120
# 1-nl-nm-ns-ynetwork-mid-0-1260-SHen-AVen-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1260

# 0-yl-ym-ys-ynetwork-mid-0-140-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 140
# 0-yl-ym-ys-ynetwork-mid-0-280-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280
# 0-yl-ym-ys-ynetwork-mid-0-420-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420
# 0-yl-ym-ys-ynetwork-mid-0-560-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560
# 0-yl-ym-ys-ynetwork-mid-0-700-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700
# 0-yl-ym-ys-ynetwork-mid-0-840-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840
# 0-yl-ym-ys-ynetwork-mid-0-980-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 980
# 0-yl-ym-ys-ynetwork-mid-0-1120-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1120
# 0-yl-ym-ys-ynetwork-mid-0-1260-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1260

# 0-nl-nm-ns-ynetwork-mid-0-140-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 140
# 0-nl-nm-ns-ynetwork-mid-0-280-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280
# 0-nl-nm-ns-ynetwork-mid-0-420-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420
# 0-nl-nm-ns-ynetwork-mid-0-560-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560
# 0-nl-nm-ns-ynetwork-mid-0-700-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700
# 0-nl-nm-ns-ynetwork-mid-0-840-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840
# 0-nl-nm-ns-ynetwork-mid-0-980-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 980
# 0-nl-nm-ns-ynetwork-mid-0-1120-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1120
# 0-nl-nm-ns-ynetwork-mid-0-1260-SHex-AVex-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1260

# 0-nl-nm-ns-ynetwork-mid-0-140-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 140
# 0-nl-nm-ns-ynetwork-mid-0-280-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280
# 0-nl-nm-ns-ynetwork-mid-0-420-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420
# 0-nl-nm-ns-ynetwork-mid-0-560-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560
# 0-nl-nm-ns-ynetwork-mid-0-700-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700
# 0-nl-nm-ns-ynetwork-mid-0-840-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840
# 0-nl-nm-ns-ynetwork-mid-0-980-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 980
# 0-nl-nm-ns-ynetwork-mid-0-1120-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1120
# 0-nl-nm-ns-ynetwork-mid-0-1260-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1260

# 0-yl-ym-ys-ynetwork-mid-0-140-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 140
# 0-yl-ym-ys-ynetwork-mid-0-280-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280
# 0-yl-ym-ys-ynetwork-mid-0-420-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420
# 0-yl-ym-ys-ynetwork-mid-0-560-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560
# 0-yl-ym-ys-ynetwork-mid-0-700-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700
# 0-yl-ym-ys-ynetwork-mid-0-840-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840
# 0-yl-ym-ys-ynetwork-mid-0-980-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 980
# 0-yl-ym-ys-ynetwork-mid-0-1120-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1120
# 0-yl-ym-ys-ynetwork-mid-0-1260-SHen-AVen-greymethanol: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1260

# 0-yl-ym-ys-ynetwork-mid-0-140-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 140
# 0-yl-ym-ys-ynetwork-mid-0-280-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280
# 0-yl-ym-ys-ynetwork-mid-0-420-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420
# 0-yl-ym-ys-ynetwork-mid-0-560-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560
# 0-yl-ym-ys-ynetwork-mid-0-700-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700
# 0-yl-ym-ys-ynetwork-mid-0-840-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840
# 0-yl-ym-ys-ynetwork-mid-0-980-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 980
# 0-yl-ym-ys-ynetwork-mid-0-1120-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1120
# 0-yl-ym-ys-ynetwork-mid-0-1260-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1260

# 0-nl-nm-ns-ynetwork-mid-0-140-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 140
# 0-nl-nm-ns-ynetwork-mid-0-280-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280
# 0-nl-nm-ns-ynetwork-mid-0-420-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420
# 0-nl-nm-ns-ynetwork-mid-0-560-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560
# 0-nl-nm-ns-ynetwork-mid-0-700-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700
# 0-nl-nm-ns-ynetwork-mid-0-840-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840
# 0-nl-nm-ns-ynetwork-mid-0-980-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 980
# 0-nl-nm-ns-ynetwork-mid-0-1120-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1120
# 0-nl-nm-ns-ynetwork-mid-0-1260-SHex-AVex-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1260

# 0-nl-nm-ns-ynetwork-mid-0-140-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 140
# 0-nl-nm-ns-ynetwork-mid-0-280-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280
# 0-nl-nm-ns-ynetwork-mid-0-420-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420
# 0-nl-nm-ns-ynetwork-mid-0-560-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560
# 0-nl-nm-ns-ynetwork-mid-0-700-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700
# 0-nl-nm-ns-ynetwork-mid-0-840-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840
# 0-nl-nm-ns-ynetwork-mid-0-980-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 980
# 0-nl-nm-ns-ynetwork-mid-0-1120-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1120
# 0-nl-nm-ns-ynetwork-mid-0-1260-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1260

3-yl-ym-ys-ynetwork-mid-0-1260-SHen-AVen-greymethanol-noimport-hvc: 
  co2_budget:
    2050: 0.000
  sector:
    co2_sequestration_potential:
      2050: 1260
# 0-yl-ym-ys-ynetwork-mid-0-140-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 140
# 0-yl-ym-ys-ynetwork-mid-0-280-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280
# 0-yl-ym-ys-ynetwork-mid-0-420-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420
# 0-yl-ym-ys-ynetwork-mid-0-560-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560
# 0-yl-ym-ys-ynetwork-mid-0-700-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700
# 0-yl-ym-ys-ynetwork-mid-0-840-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840
# 0-yl-ym-ys-ynetwork-mid-0-980-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 980
# 0-yl-ym-ys-ynetwork-mid-0-1120-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1120
# 0-yl-ym-ys-ynetwork-mid-0-1260-SHen-AVen-greymethanol-noimport: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 1260
