# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers



9-yes-mid-0-140-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 140 
    electrobiofuels: true
    e_bioSNG: true
    methanol:
      e_biomethanol: true
    EU_liquid_fuel_policy: false
9-yes-mid-0-200-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 200 
    electrobiofuels: true
    e_bioSNG: true
    methanol:
      e_biomethanol: true
    EU_liquid_fuel_policy: false
9-yes-mid-0-400-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 400 
    electrobiofuels: true
    e_bioSNG: true
    methanol:
      e_biomethanol: true
    EU_liquid_fuel_policy: false
9-yes-mid-0-600-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 600 
    electrobiofuels: true
    e_bioSNG: true
    methanol:
      e_biomethanol: true
    EU_liquid_fuel_policy: false
9-yes-mid-0-800-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 800 
    electrobiofuels: true
    e_bioSNG: true
    methanol:
      e_biomethanol: true
    EU_liquid_fuel_policy: false
9-yes-mid-0-1000-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 1000 
    electrobiofuels: true
    e_bioSNG: true
    methanol:
      e_biomethanol: true
    EU_liquid_fuel_policy: false


# 9-no-mid-0-140-nopolicy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 140 
#     electrobiofuels: false
#     e_bioSNG: false
#     methanol:
#       e_biomethanol: false
#     EU_liquid_fuel_policy: false
# 9-no-mid-0-200-nopolicy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 200 
#     electrobiofuels: false
#     e_bioSNG: false
#     methanol:
#       e_biomethanol: false
#     EU_liquid_fuel_policy: false
# 9-no-mid-0-400-nopolicy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 400 
#     electrobiofuels: false
#     e_bioSNG: false
#     methanol:
#       e_biomethanol: false
#     EU_liquid_fuel_policy: false
# 9-no-mid-0-600-nopolicy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 600 
#     electrobiofuels: false
#     e_bioSNG: false
#     methanol:
#       e_biomethanol: false
#     EU_liquid_fuel_policy: false
# 9-no-mid-0-800-nopolicy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 800 
#     electrobiofuels: false
#     e_bioSNG: false
#     methanol:
#       e_biomethanol: false
#     EU_liquid_fuel_policy: false
# 9-no-mid-0-1000-nopolicy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 1000 
#     electrobiofuels: false
#     e_bioSNG: false
#     methanol:
#       e_biomethanol: false
#     EU_liquid_fuel_policy: false



# 9-yes-mid-0-140-policy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 140 
#     electrobiofuels: true
#     e_bioSNG: true
#     methanol:
#       e_biomethanol: true
#     EU_liquid_fuel_policy: true
# 9-yes-mid-0-200-policy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 200 
#     electrobiofuels: true
#     e_bioSNG: true
#     methanol:
#       e_biomethanol: true
#     EU_liquid_fuel_policy: true
# 9-yes-mid-0-400-policy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 400 
#     electrobiofuels: true
#     e_bioSNG: true
#     methanol:
#       e_biomethanol: true
#     EU_liquid_fuel_policy: true
# 9-yes-mid-0-600-policy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 600 
#     electrobiofuels: true
#     e_bioSNG: true
#     methanol:
#       e_biomethanol: true
#     EU_liquid_fuel_policy: true
# 9-yes-mid-0-800-policy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 800 
#     electrobiofuels: true
#     e_bioSNG: true
#     methanol:
#       e_biomethanol: true
#     EU_liquid_fuel_policy: true
# 9-yes-mid-0-1000-policy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 1000 
#     electrobiofuels: true
#     e_bioSNG: true
#     methanol:
#       e_biomethanol: true
#     EU_liquid_fuel_policy: true


# 9-no-mid-0-140-policy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 140 
#     electrobiofuels: false
#     e_bioSNG: false
#     methanol:
#       e_biomethanol: false
#     EU_liquid_fuel_policy: true
# 9-no-mid-0-200-policy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 200 
#     electrobiofuels: false
#     e_bioSNG: false
#     methanol:
#       e_biomethanol: false
#     EU_liquid_fuel_policy: true
# 9-no-mid-0-400-policy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 400 
#     electrobiofuels: false
#     e_bioSNG: false
#     methanol:
#       e_biomethanol: false
#     EU_liquid_fuel_policy: true
# 9-no-mid-0-600-policy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 600 
#     electrobiofuels: false
#     e_bioSNG: false
#     methanol:
#       e_biomethanol: false
#     EU_liquid_fuel_policy: true
# 9-no-mid-0-800-policy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 800 
#     electrobiofuels: false
#     e_bioSNG: false
#     methanol:
#       e_biomethanol: false
#     EU_liquid_fuel_policy: true
# 9-no-mid-0-1000-policy: 
#   sector:
#     co2_sequestration_potential:
#       2050: 1000 
#     electrobiofuels: false
#     e_bioSNG: false
#     methanol:
#       e_biomethanol: false
#     EU_liquid_fuel_policy: true