# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers



8-no-nonetwork-0-140-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 140 
8-no-nonetwork-0-200-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 200 
8-no-nonetwork-0-250-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 250 
8-no-nonetwork-0-300-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 300 
8-no-nonetwork-0-350-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 350 
8-no-nonetwork-0-400-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 400 
8-no-nonetwork-0-600-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 600 
8-no-nonetwork-0-800-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 800 
8-no-nonetwork-0-1000-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 1000 
      