# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

S600C:
  sector:
    co2_sequestration_potential:
      2050: 600


# 0S800:
#   sector:
#     co2_sequestration_potential:
#       2050: 800

# 0S1000:
#   sector:
#     co2_sequestration_potential:
#       2050: 1000

# 0S1200:
#   sector:
#     co2_sequestration_potential:
#       2050: 1200

# 0S1400:
#   sector:
#     co2_sequestration_potential:
#       2050: 1400

    

   


   


