# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers


8-no-nonetwork-2500-H1800-200-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 200
    h2_electrolysis_limit:
      max_capacity: 1800

8-no-nonetwork-2500-H2500-200-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 200
    h2_electrolysis_limit:
      max_capacity: 2500
      
8-no-nonetwork-2500-H3500-200-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 200
    h2_electrolysis_limit:
      max_capacity: 3500

8-no-nonetwork-2500-H1800-300-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 300
    h2_electrolysis_limit:
      max_capacity: 1800

8-no-nonetwork-2500-H2500-300-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 300
    h2_electrolysis_limit:
      max_capacity: 2500
      
8-no-nonetwork-2500-H3500-300-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 300
    h2_electrolysis_limit:
      max_capacity: 3500

8-no-nonetwork-2500-H1800-500-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 500
    h2_electrolysis_limit:
      max_capacity: 1800

8-no-nonetwork-2500-H2500-500-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 500
    h2_electrolysis_limit:
      max_capacity: 2500
      
8-no-nonetwork-2500-H3500-500-nopolicy: 
  sector:
    co2_sequestration_potential:
      2050: 500
    h2_electrolysis_limit:
      max_capacity: 3500