# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers


# 1-nl-nm-ns-ynetwork-mid-0-0-SHen-AVen-2: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 0

# 1-nl-nm-ns-ynetwork-mid-0-280-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280

# 1-nl-nm-ns-ynetwork-mid-0-420-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420

# 1-nl-nm-ns-ynetwork-mid-0-560-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560

# 1-nl-nm-ns-ynetwork-mid-0-700-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700

# 1-nl-nm-ns-ynetwork-mid-0-840-SHen-AVen-2: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840

# 1-nl-nm-ns-ynetwork-mid-0-0-SHen-AVen-2: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 0

1-nl-nm-ns-ynetwork-mid-0-140-SHex-AVex: 
  co2_budget:
    2050: 0.000
  sector:
    co2_sequestration_potential:
      2050: 140

# 1-nl-nm-ns-ynetwork-mid-0-420-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420

# 1-nl-nm-ns-ynetwork-mid-0-560-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560

# 1-nl-nm-ns-ynetwork-mid-0-700-SHen-AVen: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700

# 1-nl-nm-ns-ynetwork-mid-0-840-SHen-AVen-2: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840

# 1-yl-ym-ys-ynetwork-mid-0-140-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 140
# 1-yl-ym-ys-ynetwork-mid-0-280-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 280
# 1-yl-ym-ys-ynetwork-mid-0-420-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 420
# 1-yl-ym-ys-ynetwork-mid-0-560-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 560
# 1-yl-ym-ys-ynetwork-mid-0-700-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 700
# 1-yl-ym-ys-ynetwork-mid-0-840-SHex-AVex: 
#   co2_budget:
#     2050: 0.000
#   sector:
#     co2_sequestration_potential:
#       2050: 840



# yl-ym-ys-ynetwork-mid-10-700-1.3-shipping-no: 
#   co2_budget:
#     2050: -0.100
#   sector:
#     co2_sequestration_potential:
#       2050: 700
# yl-ym-ys-ynetwork-mid-10-800-1.3-shipping-no: 
#   co2_budget:
#     2050: -0.100
#   sector:
#     co2_sequestration_potential:
#       2050: 800
# yl-ym-ys-ynetwork-mid-10-900-1.3-shipping-no: 
#   co2_budget:
#     2050: -0.100
#   sector:
#     co2_sequestration_potential:
#       2050: 900
# yl-ym-ys-ynetwork-mid-10-1000-1.3-shipping-no: 
#   co2_budget:
#     2050: -0.100
#   sector:
#     co2_sequestration_potential:
#       2050: 1000
# yl-ym-ys-ynetwork-mid-10-1100-1.3-shipping-no: 
#   co2_budget:
#     2050: -0.100
#   sector:
#     co2_sequestration_potential:
#       2050: 1100




# yl-ym-ys-ynetwork-1.5Biotran3-00-140-nordics: 
#    #countries: ['SE']
#    co2_budget:
#      2050: 0.000
#    sector:
#      co2_sequestration_potential:
#        2050: 140
