# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

# n30-2030-HT-CF-B-0-50h-mid-39nodes-with-ebfuel:  
#   #countries: ['SE']
  
#   sector:
#     H2_network: true
#     H2_retrofit: true
#     co2_network: false
#     electrobiofuels: true
#     co2_sequestration_potential:
#       2030: 0

# n30-2030-HT-CF-B-0-50h-mid-39nodes-no-ebfuel:  
#   #countries: ['SE']
  
#   sector:
#     H2_network: true
#     H2_retrofit: true
#     co2_network: false
#     electrobiofuels: false
#     co2_sequestration_potential:
#       2030: 0

# n52-2025-HT-CF-B-0-50h-mid-39nodes-with-ebfuel:  
#   #countries: ['SE']
  
#   sector:
#     H2_network: true
#     H2_retrofit: true
#     co2_network: false
#     electrobiofuels: true
#     co2_sequestration_potential:
#       2025: 0

# n52-2025-HT-CF-B-0-50h-mid-39nodes-no-ebfuel:  
#   #countries: ['SE']
  
#   sector:
#     H2_network: true
#     H2_retrofit: true
#     co2_network: false
#     electrobiofuels: false
#     co2_sequestration_potential:
#       2025: 0


# n00-2050-HF-CF-B-140-50h-mid-39nodes-with-ebfuel:  
#   #countries: ['SE']
#   co2_budget:
#     2050: 0.000
#   sector:
#     H2_network: false
#     H2_retrofit: false
#     co2_network: false
#     electrobiofuels: true
#     co2_sequestration_potential:
#       2050: 140
#n10-2050-HF-CF-B-600-50h-mid-39nodes-with-ebfuel: 
T4: 
  #countries: ['SE']
  co2_budget:
    2050: -0.100
  sector:
    # H2_network: false
    # H2_retrofit: false
    # co2_network: false
    # electrobiofuels: true
    co2_sequestration_potential:
      2050: 600

# n10-2050-HF-CF-B-800-50h-mid-39nodes-with-ebfuel:  
#   #countries: ['SE']
#   co2_budget:
#     2050: -0.100
#   sector:
#     H2_network: false
#     H2_retrofit: false
#     co2_network: false
#     electrobiofuels: true
#     co2_sequestration_potential:
#       2050: 800

# n10-2050-HF-CF-B-1000-50h-mid-39nodes-with-ebfuel:  
#   #countries: ['SE']
#   co2_budget:
#     2050: -0.100
#   sector:
#     H2_network: false
#     H2_retrofit: false
#     co2_network: false
#     electrobiofuels: true
#     co2_sequestration_potential:
#       2050: 1000
  
# n10-2050-HF-CF-B-1200-50h-mid-39nodes-with-ebfuel:  
#   #countries: ['SE']
#   co2_budget:
#     2050: -0.100
#   sector:
#     H2_network: false
#     H2_retrofit: false
#     co2_network: false
#     electrobiofuels: true
#     co2_sequestration_potential:
#       2050: 1200
    

  

#S1100_C2_in3843_1.129H_0.28_0.9C:
#  sector:
#    co2_sequestration_potential:
#      2050: 1100
#S750_C2_in3843_1.129H_0.28_0.9C:
#  sector:
 #   co2_sequestration_potential:
 #     2050: 750
  #costs:
  #  file: 
  #    "resources/costs_2050.csv"  # Update this to your specific cost file path

